name: Send a Discord message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UC4Gs81NQVfqfnfxYXm5bJ0g
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_SJY }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_SJY }}
        uses: Ilshidur/action-discord@master
        with:
          args: "`손제용의사생활 - YouTube`'\n'**${{on.youtube.outputs.title}}**'\n'${{on.youtube.outputs.link}}"
