name: Send a Discord message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UCR6sR1ITtHIz8GZqJOwqxDQ
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_SYR }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_SYR }}
        uses: Ilshidur/action-discord@master
        with:
          args: "`브레인튜브 - YouTube`'\n'**${{on.youtube.outputs.title}}**'\n'${{on.youtube.outputs.link}}"
